project_id = "hwemookrxvflpinfpkrj"

[functions.search-airports]
verify_jwt = false

[functions.test-api]
verify_jwt = false

[functions.trigger-make-webhook]
verify_jwt = false

[functions.get-make-api-key]
verify_jwt = false

[functions.parse-lead-data]
verify_jwt = false

[functions.analyze-flight-options]
verify_jwt = false