project_id = "hwemookrxvflpinfpkrj"

[functions.search-operator-aircraft]
verify_jwt = false

[functions.update-trusted-operators]
verify_jwt = false

[functions.lead-chat]
verify_jwt = false

[functions.receive-open-leg-email]
verify_jwt = false

[functions.fetch-airnav-airport]
verify_jwt = false

[functions.get-football-events]
verify_jwt = false

[functions.search-airports]
verify_jwt = false

[functions.test-api]
verify_jwt = false

[functions.trigger-make-webhook]
verify_jwt = false

[functions.validate-email]
verify_jwt = false

[functions.validate-phone]
verify_jwt = false

[functions.process-call-notes]
verify_jwt = false

[functions.get-make-api-key]
verify_jwt = false

[functions.parse-lead-data]
verify_jwt = false

[functions.calculate-average-flight-time]
verify_jwt = false

[functions.extract-airports]
verify_jwt = false

[functions.generate-flight-analysis]
verify_jwt = false

[functions.receive-lead-webhook]
verify_jwt = false

[functions.suggest-aircraft]
verify_jwt = false

[functions.process-lead-complete]
verify_jwt = false

[functions.request-charter-quotes]
verify_jwt = false

[functions.get-charter-quote-replies]
verify_jwt = false

[functions.search-charter-operators]
verify_jwt = false

[functions.get-aircraft-locations]
verify_jwt = false

[functions.get-aircraft-on-ground]
verify_jwt = false

[functions.get-charter-price]
verify_jwt = false

[functions.receive-quote-email]
verify_jwt = false

[functions.skip-trace-lead]
verify_jwt = false

[functions.parse-call-notes]
verify_jwt = false